### PR TITLE
JAMES-1852 Reorganize MIME4J side bar

### PR DESCRIPTION
**Pull request by chibenwa**
screenshot from 2016-10-27 12-08-12

### CODE REVIEW

**Review by Laura-Royet — COMMENTED** [review]
The link to the specific mime4J mailing list is missing from the side bar.

**Comment by chibenwa** [comment]
True.

**Comment by chibenwa** [comment]
screenshot from 2016-10-28 09-20-36

**Review by Laura-Royet — APPROVED** [review]

**Comment by chibenwa** [comment]
screenshot from 2016-10-28 15-50-14

**Review by Laura-Royet — APPROVED** [review]

**Review by aduprat — APPROVED** [review]

**Pull request merged**
